# https://taskfile.dev
# https://github.com/mdouchement/checksum

version: '2'

vars:
  VERSION: 0.4.2
  REVISION: { sh: git rev-parse HEAD }

env:
  CGO_ENABLED: 0

tasks:
  clean:
    desc: Clean project
    cmds:
      - rm -rf ./dist

  build-server:
    desc: Build all binaries
    cmds:
      - task: build
        vars:
          BINARY_NAME: geoblock-proxy-linux-amd64
          ENTRYPOINT: .
          TARGET_DIST: GOOS=linux GOARCH=amd64

  build-all:
    desc: Build all binaries
    cmds:
      - task: clean
      - mkdir -p ./dist

      - task: build-server

      - task: checksum
        vars:
          BINARY_NAME: geoblock-proxy-linux-amd64

      - task: build
        vars:
          BINARY_NAME: geoblock-proxy-darwin-amd64
          ENTRYPOINT: .
          TARGET_DIST: GOOS=darwin GOARCH=amd64

      - task: checksum
        vars:
          BINARY_NAME: geoblock-proxy-darwin-amd64

      - task: build
        vars:
          BINARY_NAME: geoblock-proxy-windows-amd64.exe
          ENTRYPOINT: .
          TARGET_DIST: GOOS=windows GOARCH=amd64

      - task: checksum
        vars:
          BINARY_NAME: geoblock-proxy-windows-amd64.exe

  build:
    cmds:
      - '{{.TARGET_DIST}} go build -ldflags "{{.LDFLAGS | splitList "\n" | join " "}}" -o ./dist/{{.BINARY_NAME}} {{.ENTRYPOINT}}'
    vars:
      LDFLAGS: |
        -s
        -w
        -X main.version={{.VERSION}}
        -X main.revision={{ printf "%.7s" .REVISION }}
        -X main.date={{now | date "2006-01-02~15:04:05"}}

  checksum:
    cmds:
      - cd dist && checksum --algs="sha256" --append-to checksum.txt {{.BINARY_NAME}}
